FROM python:3.12.3-alpine3.19

ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN pip install \
    -v \
    -i https://mirrors.aliyun.com/pypi/simple \
    --no-cache-dir --upgrade -r /app/requirements.txt
 
COPY ./main.py /app/main.py

# 
CMD ["uvicorn", \
    "main:app", \
    "--proxy-headers", \
    "--reload",  \
    "--access-log", \
    "--host", "0.0.0.0", "--port", "80"]